# Generated by Django 5.1.1 on 2024-09-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_delegacia', models.IntegerField()),
                ('data_ocorrencia_bo', models.DateField()),
                ('hora_ocorrencia', models.TimeField()),
                ('descr_tipolocal', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero_logradouro', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
    ]
