# Generated by Django 5.1.1 on 2024-09-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubo_celulares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roubo',
            name='bairro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roubo',
            name='cep',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roubo',
            name='cidade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roubo',
            name='hora_ocorrencia',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roubo',
            name='numero_logradouro',
            field=models.CharField(default='Número padrão', max_length=255),
        ),
    ]
