# Generated by Django 5.1.1 on 2024-09-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubo_celulares', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='experiencia',
            field=models.CharField(default='', max_length=255),
        ),
    ]
