# Generated by Django 5.1.1 on 2024-09-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubo_celulares', '0005_alter_feedback_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roubo',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roubo_celulares.bairro'),
        ),
    ]
