# Generated by Django 5.1.1 on 2024-09-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubo_celulares', '0006_alter_roubo_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='data_envio',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mensagem',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='deixar_informacao',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='experiencia',
            field=models.CharField(choices=[('excelente', 'Excelente'), ('boa', 'Boa'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='melhorias',
            field=models.CharField(choices=[('nada', 'Nada'), ('pequenas', 'Pequenas mudanças'), ('moderadas', 'Mudanças moderadas'), ('grandes', 'Mudanças grandes')], default='nada', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='nome',
            field=models.CharField(default='Anonimo', max_length=100),
        ),
    ]
